### PR TITLE
[WIP] PLC4X-193 Support for little endian types in build tools.

### PR DESCRIPTION
**Pull request by splatch**
This is work in progress.

### CODE REVIEW

**Review by chrisdutz — COMMENTED** [review]
would this be true per default for a LE protocol?

**Comment by splatch** [comment]
@chrisdutz I didn't do any grouping cause `Protocol` itself doesn't have any marks which indicate its byte order. Stage which I committed was intended to get basic handling of fields. Now when I'm working with whole types (ie. `State`/`StateIO` in amsads) it makes a sense to introduce a protocol level switch.

**Comment by chrisdutz** [comment]
Hi Lukasz ... well this protocol level switch is already there ... if you initialize the Read and WriteBuffers as BE or LE.

**Comment by splatch** [comment]
This PR is not relevant any more due to mentioned ability of `ReadBuffer` and `WriteBuffer`.

**Pull request closed without merging**
